# Generated by Django 4.0.3 on 2022-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Unknown')], default=0),
        ),
    ]
