# Generated by Django 4.0.3 on 2022-03-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='yourChoice',
            new_name='choices',
        ),
    ]
