# Generated by Django 4.0.3 on 2022-04-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Unknown')], default=2),
        ),
    ]
