# Generated by Django 4.0.3 on 2022-03-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_alter_question_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='title',
        ),
    ]
